config/routes.rb
Rails.application.routes.draw do
  
  # Pages
  root 'pages#home'
  get '/cart', to: 'pages#cart', as: 'cart'
  # Carts
  get 'carts/show'
  post '/carts/:id_product', to: 'carts#add_product', as: 'add_product_to_cart'
  

  namespace :admin do
    # Categories
  #VERB     URI                       RESPONSABLE           ALIAS
    get 'categories',           to: 'categories#index', as: 'categories'
    get 'categories/new',       to: 'categories#new',   as: 'new_category'
    get 'categories/:id',       to: 'categories#show',  as: 'category'
    get 'categories/:id/edit',  to: 'categories#edit',  as: 'edit_category'

    post    'categories',         to: 'categories#create'
    put     'categories/:id',     to: 'categories#update'
    patch   'categories/:id',     to: 'categories#update'
    delete  'categories/:id',     to: 'categories#destroy'

    # Roles
    get 'roles',          to: 'roles#index',    as: 'roles'
    get 'roles/new',      to: 'roles#new',      as: 'new_role'
    get 'roles/:id',      to: 'roles#show',     as: 'role'
    get 'roles/:id/edit', to: 'roles#edit',     as: 'edit_role'

    post    'roles',          to: 'roles#create'
    put     'roles/:id',      to: 'roles#update'
    patch   'roles/:id',      to: 'roles#update'
    delete  'roles/:id',      to: 'roles#destroy'

    # # Statuses

    # get 'statuses',             to: 'statuses#index',   as: 'statuses'
    # get 'statuses/new',         to: 'statuses#new',     as: 'new_status'
    # get 'statuses/:id',         to: 'statuses#show',    as: 'status'
    # get 'statuses/:id/edit',    to: 'statuses#edit',    as: 'edit_status'

    # post    'statuses',            to: 'statuses#create'
    # put     'statuses/:id',        to: 'statuses#update'
    # patch    'statuses/:id',        to: 'statuses#update'
    # delete  'statuses/:id',        to: 'statuses#destroy'

      # Statuses

      get 'estados',             to: 'estados#index',   as: 'estados'
      get 'estados/new',         to: 'estados#new',     as: 'new_estado'
      get 'estados/:id',         to: 'estados#show',    as: 'estado'
      get 'estados/:id/edit',    to: 'estados#edit',    as: 'edit_estado'
  
      post    'estados',            to: 'estados#create'
      put     'estados/:id',        to: 'estados#update'
      patch    'estados/:id',        to: 'estados#update'
      delete  'estados/:id',        to: 'estados#destroy'
    # Products

    get 'products',             to: 'products#index', as: 'products'
    get 'products/new',         to: 'products#new',   as: 'new_product'
    get 'products/:id',         to: 'products#show',  as: 'product'
    get 'products/:id/edit',    to: 'products#edit',  as: 'edit_product'

    post    'products',           to: 'products#create'
    put     'products/:id',       to: 'products#update'
    patch   'products/:id',       to: 'products#update'
    delete  'products/:id',       to: 'products#destroy'
  end

end

app/models/estado.rb
class Estado < ApplicationRecord
    has_many :orders

    validates :description, presence: true, uniqueness: true
end

app/controllers/admin/estados_controller.rb
class Admin::EstadosController < ApplicationController
  
  layout 'admin_layout'
  before_action :set_estado, only: [:show, :edit, :update, :destroy]
  
#GET  /ROLES
  def index
    @estados = Estado.all
  end

#GET /ROLES/NEW
  def new
    @estado = Estado.new
  end

#GET /ROLES/:ID
  def show
  end

#GET /ROLES/:ID/EDIT
  def edit
  end

# POST /ROLES
  def create
    @estado = Estado.new(params_estado)
    if @estado.save
      redirect_to admin_estados_path
    else
      render :new
    end
  end

# PUT / PATCH  /ROLES/:ID
  def update
    if @estado.update(params_estado)
      redirect_to admin_estado_path
    else
      render :edit
    end
  end

#DELETE /ROLES/:ID
  def destroy
    @estado.destroy
    redirect_to admin_estado_path
  end

  private
  def params_estado
    params.require(:estado).permit(:description)
  end

  def set_estado
    @estado = Estado.find(params[:id])
  rescue
    # el flash es como el mensajero de rails
    flash[:set_estado_error] = "Could not find the record #{params[:id]}"
    redirect_to admin_estados_path
  end

end

app/helpers/admin/estados_helper.rb
module Admin::EstadosHelper
end

app/views/admin/estados/_form.html.erb
<!-- VARIABLES: base_estado -->
<div class="card">
  <div class="card-body">
    <%= form_with(model: [:admin, base_estado]) do |form| %>
        
        <div class="mb-3">
            <%= form.label :name, class: 'form-label' %>
            <%= form.text_field :name, class: 'form-control' %>
            <% if base_estado.errors[:name].any? %>
              <div>
                <%= base_estado.errors[:na].first %>
              </div>
            <% end %>
        </div>

        <%= form.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/admin/estados/edit.html.erb
<h1>Admin::Estados#edit</h1>
<%= render "form", base_estado: @estado %>

app/views/admin/estados/index.html.erb
<h1>Admin::Estados#index</h1>
<div class="card">
  <div class="card-body">
    <h5  class="card-title"> Index </h5>
    <%= link_to "New", admin_new_estado_path, class: 'btn btn-primary' %>
    <% if flash[:set_estado_error] %>
      <%= flash[:set_estado_error] %>
    <% end %>

    <table class="table table-hover">
      <tr>
        <th> Description </th>
        <th> Action </th>
      </tr>
      <% @estados.each do |c| %>
        <tr>
          <td> <%= c.description %> </td>
          <td>
              <%= link_to "Edit", admin_edit_estado_path(c) %>
              <%= link_to "Delete", admin_estado_path(c), method: :delete %>
          </td>
        </tr>
      <% end %>
    </table>

  </div>
</div>

app/views/admin/estados/new.html.erb
<h1>Admin::Estados#new</h1>
<%= render "form", base_estado: @estado %>

app/views/admin/estados/show.html.erb
<h1>Admin::Estados#show</h1>
<p>Find me in app/views/admin/estados/show.html.erb</p>