config/routes.rb
Rails.application.routes.draw do
  
  # Pages
  root 'pages#home'
  get '/cart', to: 'pages#cart', as: 'cart'
  # Carts
  get 'carts/show'
  post '/carts/:id_product', to: 'carts#add_product', as: 'add_product_to_cart'
  

  namespace :admin do
    # Categories
  #VERB     URI                       RESPONSABLE           ALIAS
    get 'categories',           to: 'categories#index', as: 'categories'
    get 'categories/new',       to: 'categories#new',   as: 'new_category'
    get 'categories/:id',       to: 'categories#show',  as: 'category'
    get 'categories/:id/edit',  to: 'categories#edit',  as: 'edit_category'

    post    'categories',         to: 'categories#create'
    put     'categories/:id',     to: 'categories#update'
    patch   'categories/:id',     to: 'categories#update'
    delete  'categories/:id',     to: 'categories#destroy'

    # Roles
    get 'roles',          to: 'roles#index',    as: 'roles'
    get 'roles/new',      to: 'roles#new',      as: 'new_role'
    get 'roles/:id',      to: 'roles#show',     as: 'role'
    get 'roles/:id/edit', to: 'roles#edit',     as: 'edit_role'

    post    'roles',          to: 'roles#create'
    put     'roles/:id',      to: 'roles#update'
    patch   'roles/:id',      to: 'roles#update'
    delete  'roles/:id',      to: 'roles#destroy'

    # # Statuses

    # get 'statuses',             to: 'statuses#index',   as: 'statuses'
    # get 'statuses/new',         to: 'statuses#new',     as: 'new_status'
    # get 'statuses/:id',         to: 'statuses#show',    as: 'status'
    # get 'statuses/:id/edit',    to: 'statuses#edit',    as: 'edit_status'

    # post    'statuses',            to: 'statuses#create'
    # put     'statuses/:id',        to: 'statuses#update'
    # patch    'statuses/:id',        to: 'statuses#update'
    # delete  'statuses/:id',        to: 'statuses#destroy'

      # Statuses

      get 'estados',             to: 'estados#index',   as: 'estados'
      get 'estados/new',         to: 'estados#new',     as: 'new_estado'
      get 'estados/:id',         to: 'estados#show',    as: 'estado'
      get 'estados/:id/edit',    to: 'estados#edit',    as: 'edit_estado'
  
      post    'estados',            to: 'estados#create'
      put     'estados/:id',        to: 'estados#update'
      patch    'estados/:id',        to: 'estados#update'
      delete  'estados/:id',        to: 'estados#destroy'
    # Products

    get 'products',             to: 'products#index', as: 'products'
    get 'products/new',         to: 'products#new',   as: 'new_product'
    get 'products/:id',         to: 'products#show',  as: 'product'
    get 'products/:id/edit',    to: 'products#edit',  as: 'edit_product'

    post    'products',           to: 'products#create'
    put     'products/:id',       to: 'products#update'
    patch   'products/:id',       to: 'products#update'
    delete  'products/:id',       to: 'products#destroy'
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_details
  has_many :orders, through: :order_details
  has_many :cart_products
  has_many :carts, through: :cart_products

  validates :name, presence: true
  validates :price, presence: true, numericality: true
  validates :description, presence: true
  validates :category_id, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin_layout"  
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def index
    #@products = Product.all # problema n+1
    @products = Product.includes(:category)
  end
  
  def new
    @product = Product.new
    set_categories
  end

  def show
  end

  def edit
    set_categories
  end

  def create
    @product = Product.new(params_product)
    if @product.save
      redirect_to admin_products_path
    else
      set_categories
      render :new
    end
  end

  def update
    if @product.update(params_product)
      redirect_to admin_products_path
    else
      set_categories
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path

  end

  private
  def set_product
    @product = Product.find(params[:id])
  rescue
    flash[:set_product_error] = "Could not find the record #{params[:id]}"
    redirect_to admin_products_path
  end

  def params_product
    params.require(:product).permit(:name, :price, :description, :category_id)
  end

  def set_categories
    @categories = Category.all
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<!-- VARIABLES: base_product ; categories -->

<div class="card">
  
    <%= form_with(model: [:admin, base_product]) do |form| %>
        
        <div class="mb-3">
            <%= form.label :name, class: 'form-label' %>
            <%= form.text_field :name, class: 'form-control' %>
             <% if base_product.errors[:name].any? %>
              <div>
                <%= base_product.errors[:name].first %>
              </div>
            <% end %>
            <%= form.label :price, class: 'form-label' %>
            <%= form.text_field :price, class: 'form-control' %>
            <% if base_product.errors[:price].any? %>
              <div>
                <%= base_product.errors[:price].first %>
              </div>
            <% end %>
            
            <%= form.label :description, class: 'form-label' %>
            <%= form.text_field :description, class: 'form-control' %>
             <% if base_product.errors[:description].any? %>
              <div>
                <%= base_product.errors[:description].first %>
              </div>
            <% end %>
            
            <!-- <%= form.label :categories_id, class: 'form-label' %>-->
            <!-- <%= form.collection_select(:category_id, Category.all, :id, :name) %> -->
            
            <%= form.label  :category_id, class: 'form-label' %>
            <%= form.select :category_id,
            options_from_collection_for_select(@categories, :id, :name, base_product.category_id),
             { include_blank: "Select a category" },
              {class: 'form-control'} %>

            <% if base_product.errors[:category_id].any? %>
              <div>
                <%= base_product.errors[:category_id].first %>
              </div>
            <% end %>
        </div>

        <%= form.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/admin/products/edit.html.erb
<h1>Admin::Products#edit</h1>

<%= render "form", base_product: @product, categories: @categories  %>

app/views/admin/products/index.html.erb
<h3>Products</h3>

<div class="card">
    <div class="card-body">
        <h5> Index </h5>
        <%= link_to "New", admin_new_product_path, class: 'btn btn-primary' %>
        <% if flash[:set_product_error] %>
            <%= flash[:set_product_error] %>
        <% end %>

        <table class="table table-hover">
            <tr>
                <th> Name </th>
                <th> Price USD </th>
                <th> Description </th>
                <th> Category </th>
                <th> Action </th>
            </tr>
            <% @products.each do |p| %>
                <tr>
                    <td> <%= p.name %> </td>
                    <td> <%= p.price  %> </td>
                    <td> <%= p.description  %> </td>
                    <td> <%= p.category.name  %> </td>
                    <td>
                        <%= link_to "Edit", admin_edit_product_path(p), class: 'btn btn-warning'  %>
                        <%= link_to "Delete", admin_product_path(p), class: 'btn btn-warning', method: :delete, data: { confirm: "Are you sure?" }  %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>
</div>

app/views/admin/products/new.html.erb
<h1>Admin::Products#new</h1>

<%= render "form", base_product: @product, categories: @categories  %>

app/views/admin/products/show.html.erb
<h1>Admin::Products#show</h1>
<ul>
    <li> <%= @product.price %> </li>
    <li> <%= @product.description %> </li>
    <li> <%= @produt.category.name %> </li>
</ul>