config/routes.rb
Rails.application.routes.draw do
  
  # Pages
  root 'pages#home'
  get '/cart', to: 'pages#cart', as: 'cart'
  # Carts
  get 'carts/show'
  post '/carts/:id_product', to: 'carts#add_product', as: 'add_product_to_cart'
  

  namespace :admin do
    # Categories
  #VERB     URI                       RESPONSABLE           ALIAS
    get 'categories',           to: 'categories#index', as: 'categories'
    get 'categories/new',       to: 'categories#new',   as: 'new_category'
    get 'categories/:id',       to: 'categories#show',  as: 'category'
    get 'categories/:id/edit',  to: 'categories#edit',  as: 'edit_category'

    post    'categories',         to: 'categories#create'
    put     'categories/:id',     to: 'categories#update'
    patch   'categories/:id',     to: 'categories#update'
    delete  'categories/:id',     to: 'categories#destroy'

    # Roles
    get 'roles',          to: 'roles#index',    as: 'roles'
    get 'roles/new',      to: 'roles#new',      as: 'new_role'
    get 'roles/:id',      to: 'roles#show',     as: 'role'
    get 'roles/:id/edit', to: 'roles#edit',     as: 'edit_role'

    post    'roles',          to: 'roles#create'
    put     'roles/:id',      to: 'roles#update'
    patch   'roles/:id',      to: 'roles#update'
    delete  'roles/:id',      to: 'roles#destroy'

    # # Statuses

    # get 'statuses',             to: 'statuses#index',   as: 'statuses'
    # get 'statuses/new',         to: 'statuses#new',     as: 'new_status'
    # get 'statuses/:id',         to: 'statuses#show',    as: 'status'
    # get 'statuses/:id/edit',    to: 'statuses#edit',    as: 'edit_status'

    # post    'statuses',            to: 'statuses#create'
    # put     'statuses/:id',        to: 'statuses#update'
    # patch    'statuses/:id',        to: 'statuses#update'
    # delete  'statuses/:id',        to: 'statuses#destroy'

      # Statuses

      get 'estados',             to: 'estados#index',   as: 'estados'
      get 'estados/new',         to: 'estados#new',     as: 'new_estado'
      get 'estados/:id',         to: 'estados#show',    as: 'estado'
      get 'estados/:id/edit',    to: 'estados#edit',    as: 'edit_estado'
  
      post    'estados',            to: 'estados#create'
      put     'estados/:id',        to: 'estados#update'
      patch    'estados/:id',        to: 'estados#update'
      delete  'estados/:id',        to: 'estados#destroy'
    # Products

    get 'products',             to: 'products#index', as: 'products'
    get 'products/new',         to: 'products#new',   as: 'new_product'
    get 'products/:id',         to: 'products#show',  as: 'product'
    get 'products/:id/edit',    to: 'products#edit',  as: 'edit_product'

    post    'products',           to: 'products#create'
    put     'products/:id',       to: 'products#update'
    patch   'products/:id',       to: 'products#update'
    delete  'products/:id',       to: 'products#destroy'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_products
    has_many :products, through: :cart_products

    validates :total, presence: true, numericality: true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  validates :cart_id, presence: true
  validates :product_id, presence: true
  validates :quantity, presence: true, numericality: true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :name, presence: true, uniqueness: true
end

app/models/estado.rb
class Estado < ApplicationRecord
    has_many :orders

    validates :description, presence: true, uniqueness: true
end

app/models/kart.rb
class Kart < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  
    belongs_to :user, optional: true
    belongs_to :status
    has_many :order_details
    has_many :products, through: :order_details
    
    # todo: revisar generación del número del pedido
    validates :number, presence: true, numericality: true, uniqueness: true
    validates :total, presence: true, numericality: true
    validates :status_id, presence: true
  end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :order_id,    presence: true
  validates :product_id,  presence: true
  validates :quantity,    presence: true, numericality: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_details
  has_many :orders, through: :order_details
  has_many :cart_products
  has_many :carts, through: :cart_products

  validates :name, presence: true
  validates :price, presence: true, numericality: true
  validates :description, presence: true
  validates :category_id, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users

    validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :role
  has_many :orders

  validates :username, presence: true, uniqueness: true
  validates :role_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  include PagesHelper
  before_action :set_cart_from_cookie # nos asginar la variable @cart

  def show
  end

  # POST /carts/:id_product
  def add_product
    # recuperar el id de cart -> cookie
    # recuperar el id del product
    # guardar el registro en CartProduct
    cart_product = CartProduct.new
    cart_product.cart = @cart
    cart_product.product_id = params[:id_product]
    cart_product.quantity = 1
    cart_product.save

    flash[:cart_product_created] = "Product added"
    redirect_to root_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  include PagesHelper
  before_action :set_cart_from_cookie

  def home  
    @products = Product.includes(:category).shuffle
  end

  def cart
  end  

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  # almacenar métodos
    # almacenar lógica
  # almacenar clases

    def cookies_handler
        if cookies[:plana]
          puts cookies[:plana]
        else
          cookies[:plana] = "COOKIE PLANA 🥞"
        end
      
        if cookies.signed[:firmada]
          puts cookies.signed[:firmada]
        else
          cookies.signed[:firmada] = "Hola mundo FIRMADO 🍕"
        end
    
        if cookies.encrypted[:encriptada]
          puts cookies.encrypted[:encriptada]
        else
          cookies.encrypted[:encriptada] = "TEXTO SECRETO 🍔"
        end
    
        if session[:variable_sesion]
          puts session[:variable_sesion]
        else
          session[:variable_sesion] = "EN LA SESION 🥓"
        end
    end

    def print_icon
      puts "🖨".center(50, "-")
    end

    def set_cart_from_cookie
      # 1. Preguntar si existe la variable cookies[:cart_id]
      if cookies[:cart_id]
        # SI existe: Buscar el registro de Cart según el cookies[:cart_id]
        # definir una variable @cart
        @cart = Cart.find(cookies[:cart_id])
      else
        # SINO existe: Crear un registro en Cart
        # asignar la cookie con el id
        @cart = Cart.create(total: 0)
        cookies[:cart_id] = @cart.id
      end
    end
    
end

app/views/layouts/_horizontal_menu.html.erb
   
<nav class="navbar fixed-top navbar-light bg-primary">
    <div class="container">
        <div class="row align-items-center w-100">
            <div class="col-lg-2">
                <a class="navbar-brand fs-3" href="/">Carts $ Cars</a>
            </div>
            <div class="col-lg-8">
                <%= form_with(method: :get) do |form| %>
                    <%= form.text_field :search, class: 'form-control', placeholder: 'search' %>
                <% end %>
            </div>
            <div class="col-lg-2 text-center">
                <%= link_to cart_path, class: 'text-decoration-none text-dark btn-cart fs-5' do %>
                    <i class="bi bi-cart3"></i>
                    <%= @cart.cart_products.count %>
                <% end %>
            </div>
        </div>
    </div>
  </nav>

app/views/layouts/_vertical_es.html.erb
<div class="fixed-top vertical-menu d-flex flex-column flex-shrink-0 p-3 text-dark bg-dark col-2">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4">Sidebar</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="#" class="nav-link active" aria-current="page">
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                Home
            </a>
        </li>
        <li>
            <%= link_to admin_categories_path, class: "nav-link text-white" do %>
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
                Categories
            <% end %>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
                Orders
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
                Products
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
                Customers
            </a>
        </li>
    </ul>
    <hr>
    <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/genmistic.png" alt="" width="40" height="40" class="rounded-circle me-2">
            <strong>Luis</strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="#">New project...</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Sign out</a></li>
        </ul>
    </div>
</div>

app/views/layouts/_vertical_menu.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4">Sidebar</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="#" class="nav-link active" aria-current="page">
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                Home
            </a>
        </li>
        <li class="mb-1">
            <%= link_to admin_categories_path, class: "nav-link text-white" do %>
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
                Categories
            <% end %>
        </li>
        <li>
            <%= link_to admin_roles_path, class: "nav-link text-white" do %>
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
                Roles
            <% end %>
        </li>
        <li>
             <%= link_to admin_products_path, class: "nav-link text-white" do %>
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
                Products
            <% end %>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
                Customers
            </a>
        </li>
    </ul>
    <hr>
    <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/genmistic.png" alt="" width="40" height="40" class="rounded-circle me-2">
            <strong>Luis</strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="#">New project...</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Sign out</a></li>
        </ul>
    </div>
</div>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="row">
        <div class="col-3">
          <%= render "layouts/vertical_menu" %>
        </div>
        <div class="col-9">
          <div class="container">
              <%= yield %>
          </div>
        </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/horizontal_menu" %>
    <div class="container mt-5 pt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_product_card.html.erb
<!-- VARIABLES: base_product -->
<div class="card w-100">
    <div class="card-body">
    
     
        <h5>
            <%= base_product.name %>
        </h5>
        <h6 class="text-muted">
            <%= base_product.category.name %>
        </h6>
        <p>
            <%= base_product.description %>
        </p>

        <%= link_to add_product_to_cart_path(base_product), method: :post, class: 'btn btn-secondary', data: { confirm: 'Add to the cart?' } do %>
            <i class="bi bi-cart-plus"></i>
            <%= base_product.price.to_s(:delimited) %> USD
        <% end %>
    </div>
</div>

app/views/pages/cart.html.erb
<div class="row">
    <% @products.each do |p| %>    
        <div class="col-3 mb-3">
            <%= render 'product_card', base_product: p %>
        </div>
    <% end %>
</div>

app/views/pages/home.html.erb
<div class="row">
    <% @products.each do |p| %>    
        <div class="col-3 mb-3">
            <%= render 'product_card', base_product: p %>
        </div>
    <% end %>
</div>